# Discord Stuff
enabled: true # Enable discord bot?
token: "" # Discord bot token
server: "" # ID of discord server

# ID of channel where match embeds will be sent
match-channel: ""

# URL where map images are stored
map-images-url: ""